### ISSUE TITLE
This task uses Node 6 execution handler

### ISSUE THREAD

**Issue by franz-ms-muc** [sonarsource-cfamily-examples/linux-cmake-azure-sc#10]
##\[warning\]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - [https://aka.ms/migrateTaskNode10.](https://aka.ms/migrateTaskNode10.) If you are the user - feel free to reach out to the owners of this task to proceed on migration.   
 

https://dev.azure.com/test-sonar/linux-cmake-azure-sc/_build/results?buildId=10&view=logs&j=ba12d578-4c1d-529a-8259-df4d1ac6f9f3&t=dcff099d-bd57-53d2-2d17-be172642e053&l=11

**Comment by franz-ms-muc** [comment]
https://community.sonarsource.com/t/sonarcloud-prepare-task-uses-node-6-tasks/44223/16

**Comment by amelie-renard-sonarsource** [comment]
Thanks @franz-ms-muc for raising the issue. 
The migration has been done and the task now uses Node10.
